Integration of functions for plots
sales-lab/spatialDE pull request #18
Opened 2021-06-21 09:46 UTC by davidecrs

Added functions for plots. 
Thanks to  @lambdamoses

- `FSV_sig`: Plot Fraction Spatial Variance vs Q-value
- `multiGenePlots`: Plot Spatial Patterns of Multiple Genes. Integrated with S4 method for `matrix` and `SpatialExperiment` object

Close #4

2021-06-22 17:21 UTC, milanmlft requested changes
This looks good to me! I will just push some small updates to format the code in "BioConductor" style and some small improvements to the vignette.

The only thing that's missing is an example in the documentation of `FSV_sig` I think.

2021-06-22 17:21 UTC, milanmlft commented on R/plots.R
> +#' Plot Fraction Spatial Variance vs Q-value
We should provide a small example in the documentation of this function

2021-06-22 19:09 UTC, lambdamoses commented
I wonder if the data wrangling should be rewritten with base R to get rid of the dplyr and magrittr dependencies, though I trust that dplyr and magrittr are very unlikely to introduce breaking changes.

2021-06-22 19:18 UTC, lambdamoses approved these changes

2021-06-23 07:27 UTC, milanmlft commented
> I wonder if the data wrangling should be rewritten with base R to get rid of the dplyr and magrittr dependencies, though I trust that dplyr and magrittr are very unlikely to introduce breaking changes.

I agree, they're only used in a few places, so removing them as dependency would make sense.

2021-06-23 09:13 UTC, milanmlft approved these changes

2021-06-23 19:47 UTC, lambdamoses reviewed
I'll rewrite the Tidyverse code with base R.

2021-06-25 08:04 UTC, merged